"""empty message

Revision ID: 0e023dbb322a
Revises: 8fdf317667ef
Create Date: 2022-02-04 08:21:41.387285

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = '0e023dbb322a'
down_revision = '8fdf317667ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'vehicles', ['VIN'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'vehicles', type_='unique')
    # ### end Alembic commands ###
