"""empty message

Revision ID: 42763b8edfc3
Revises: 20db2d9af2dd
Create Date: 2022-02-04 07:59:54.318080

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '42763b8edfc3'
down_revision = '20db2d9af2dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('drivers',
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('first_lastname', sa.String(length=120), nullable=True),
    sa.Column('second_lastname', sa.String(length=120), nullable=True),
    sa.Column('dob', sa.DateTime(), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('phone', sa.String(length=10), nullable=True),
    sa.Column('credential_type', sa.String(length=5), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.drop_index('email', table_name='driver')
    op.drop_table('driver')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('driver',
    sa.Column('id', mysql.CHAR(length=32), nullable=False),
    sa.Column('name', mysql.VARCHAR(length=120), nullable=True),
    sa.Column('first_lastname', mysql.VARCHAR(length=120), nullable=True),
    sa.Column('second_lastname', mysql.VARCHAR(length=120), nullable=True),
    sa.Column('email', mysql.VARCHAR(length=120), nullable=True),
    sa.Column('phone', mysql.VARCHAR(length=10), nullable=True),
    sa.Column('credential_type', mysql.VARCHAR(length=5), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.Column('dob', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_index('email', 'driver', ['email'], unique=False)
    op.drop_table('drivers')
    # ### end Alembic commands ###
